version: "2"

linters:
  default: none
  enable:
    - revive
    - govet
    - errcheck
    - ineffassign
    - unconvert
    - misspell
    - prealloc
    - gosec
    - staticcheck
    - unused

  settings:
    govet:
      enable:
        - shadow

    errcheck:
      check-blank: true
      check-type-assertions: true

    revive:
      # Use recommended configuration
      # @see https://github.com/mgechev/revive#recommended-configuration
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

formatters:
  enable:
    - gofmt
    - goimports
