version: 2

project_name: tanuki

before:
  hooks:
    - go mod tidy

builds:
  - id: tanuki
    main: ./cmd/tanuki
    binary: tanuki
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/bkonkle/tanuki/internal/cli.version={{.Version}}
      - -X github.com/bkonkle/tanuki/internal/cli.commit={{.Commit}}
      - -X github.com/bkonkle/tanuki/internal/cli.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: bkonkle
    name: tanuki
  draft: true
  prerelease: auto
